# 言語学B

方言と地域の関連

引っ張ったデータ
- [『方言談話資料』データ](https://mmsrv.ninjal.ac.jp/hogendanwa_siryo/)


In [1]:
split_text_example = ['｜日本語｜にほんご｜Japanese｜', '0302206|Ａ|メス　カネデ。|飯〔を〕　食わないで。', "0302311|Ｂ|〈ベント　モッテ　エッテナ〉。アノー　スノリヅル　スノリー　ドロドロテ　スノリナー。（Ａ　Ｃ　ウーン）　アエ　ニデ　オツユニステヨー　ウン　（Ａ　Ｃ　ウン）　《笑》　マー　ススルンダナ　マヅナー　《笑》。ステ　コンダ　ビンサ　ツメデ　ウン　テ［10］　スノリヅル　カゲデ　ホラ　ウン　（Ａ　ウンウウン　ホンダ　ホンダ。Ｃ　ウン）　ウン　カポエデナ　ウン。【オキー　オ】　トン＾ヅノ　オキ　タサ　ハッテヨー　　ウン。｜弁当〔を〕　持って　行ってな。あのう　布海苔汁　布海苔　どろどろして　布海苔なあ。（Ａ　Ｃ　うーん）　あれ〔を〕　煮て　おつゆにしてよう　うん　（Ａ　Ｃ　うん）　《笑》　まあ　すするんだな　まずなあ　《笑》。そして　今度　瓶に　詰めて　うん　そして　布海苔汁〔を〕　かけて　ほら　うん　（Ａ　うんうんうん　そうだ　そうだ　Ｃ　うん）　うん　急いで食ってな　うん。当時の　大きい　田に　入ってよう　うん。"]

# 各文字列に対して、`|`, `｜` で split で分割する

for line in split_text_example:
    line = line.replace('｜', '|')
    splited_line = line.split('|')
    print(splited_line)

['', '日本語', 'にほんご', 'Japanese', '']
['0302206', 'Ａ', 'メス\u3000カネデ。', '飯〔を〕\u3000食わないで。']
['0302311', 'Ｂ', '〈ベント\u3000モッテ\u3000エッテナ〉。アノー\u3000スノリヅル\u3000スノリー\u3000ドロドロテ\u3000スノリナー。（Ａ\u3000Ｃ\u3000ウーン）\u3000アエ\u3000ニデ\u3000オツユニステヨー\u3000ウン\u3000（Ａ\u3000Ｃ\u3000ウン）\u3000《笑》\u3000マー\u3000ススルンダナ\u3000マヅナー\u3000《笑》。ステ\u3000コンダ\u3000ビンサ\u3000ツメデ\u3000ウン\u3000テ［10］\u3000スノリヅル\u3000カゲデ\u3000ホラ\u3000ウン\u3000（Ａ\u3000ウンウウン\u3000ホンダ\u3000ホンダ。Ｃ\u3000ウン）\u3000ウン\u3000カポエデナ\u3000ウン。【オキー\u3000オ】\u3000トン＾ヅノ\u3000オキ\u3000タサ\u3000ハッテヨー\u3000\u3000ウン。', '弁当〔を〕\u3000持って\u3000行ってな。あのう\u3000布海苔汁\u3000布海苔\u3000どろどろして\u3000布海苔なあ。（Ａ\u3000Ｃ\u3000うーん）\u3000あれ〔を〕\u3000煮て\u3000おつゆにしてよう\u3000うん\u3000（Ａ\u3000Ｃ\u3000うん）\u3000《笑》\u3000まあ\u3000すするんだな\u3000まずなあ\u3000《笑》。そして\u3000今度\u3000瓶に\u3000詰めて\u3000うん\u3000そして\u3000布海苔汁〔を〕\u3000かけて\u3000ほら\u3000うん\u3000（Ａ\u3000うんうんうん\u3000そうだ\u3000そうだ\u3000Ｃ\u3000うん）\u3000うん\u3000急いで食ってな\u3000うん。当時の\u3000大きい\u3000田に\u3000入ってよう\u3000うん。']


In [2]:
# shift-JIS
# ファイル名は `01Ⅰ山形03` の形式
# 適宜エラーハンドリングを追加する

import os

number_of_pref = 19
pref = ["山形", "群馬", "長野", "奈良", "高知", "長崎", "青森", "新潟", "愛知", "福井", "京都", "島根", "岩手", "宮城", "千葉", "静岡", "鳥取", "愛媛", "宮崎"]
number_of_file = [16, 11, 3, 2, 8, 12, 9, 5, 3, 10, 9, 8, 2, 8, 1, 9, 2, 1, 6]
fold_number = [1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6]
file_number = [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 4, 1, 2, 3]
roman_number = ["Ⅰ", "Ⅱ", "Ⅲ", "Ⅰ", "Ⅱ", "Ⅲ", "Ⅰ", "Ⅱ", "Ⅲ", "Ⅰ", "Ⅱ", "Ⅲ", "Ⅰ", "Ⅱ", "Ⅲ", "Ⅳ", "Ⅰ", "Ⅱ", "Ⅲ"]

# 与えられた文字列のうち、かっこで囲まれた部分を除外する関数
def remove_brackets(text):
    brackets = [("〔", "〕"), ("「", "」"), ("［", "］"), ("【", "】"), ("｛", "｝"), ("《", "》"), ("（", "）"), ("〈", "〉"), ("[", "]"), ("{", "}"), ("(", ")"), ("<", ">")]
    for start_bracket, end_bracket in brackets:
        while True:
            start = text.find(start_bracket)
            if start == -1:
                break
            end = text.find(end_bracket, start)
            if end == -1:
                break
            text = text[:start] + text[end+1:]
    return text

# 与えられた文字列のうち、カタカナだけを抽出する関数
def extract_katakana(text):
    katakana = ""
    for c in text:
        if c not in "～※“”＊…　、。＾ ーッ？！⌒・「」『』〈〉【】［］≪≫《》〔〕（）｛｝〓" and c not in "[]{}()<>0123456789~":
            katakana += c
    return katakana

# テキストファイルに対して、会話文のみ抽出する関数
def extract_talk_and_write(input_file_path, katakana_file_path):
    lines = []
    try:
        with open(input_file_path, "r", encoding="shift-JIS") as f:
            lines = f.readlines()
    except Exception as e:
        print(f"Error reading {input_file_path}: {e}")
        return
    try:
        with open(katakana_file_path, "w", encoding="shift-JIS") as f:
            for line in lines:
                print("#", end="")
                # "|" が含まれていない行はスキップ
                if "|" not in line and "｜" not in line:
                    continue
                # 2つ目と3つ目の `|` もしくは `｜` の文字で囲まれた部分が会話文
                line = line.replace('｜', '|')
                text = line.split('|')[2]
                # 会話文のうち、カタカナだけを抽出
                text = extract_katakana(text)
                # 会話文が空でなければ書き込む
                if text != "":
                    f.write(text + "\n")
            print("")
    except Exception as e:
        print(f"Error writing {katakana_file_path}: {e}")
        return

os.makedirs("./katakana/", exist_ok=True)

# ファイルを読み込んで会話文のみ抽出して書き込む
for pr in range(number_of_pref):
    os.makedirs("./katakana/" + pref[pr], exist_ok=True)
    if number_of_file[pr] == 0:
        continue
    if number_of_file[pr] == 1:
        print(pref[pr] + " 01: start")
        input_file_path = "./input/" + pref[pr] + "/" + "{:02}".format(fold_number[pr]) + roman_number[pr] + pref[pr] + ".txt"
        print(input_file_path)
        katakana_file_path = "./katakana/" + pref[pr] + "/talk01.txt"
        print(katakana_file_path)
        extract_talk_and_write(input_file_path, katakana_file_path)
        print(pref[pr] + " 01: done")
        continue
    for i in range(number_of_file[pr]):
        print(pref[pr] + " " + "{:02}".format(i+1) + ": start")
        input_file_path = "./input/" + pref[pr] + "/" + "{:02}".format(fold_number[pr]) + roman_number[pr] + pref[pr] + "{:02}".format(i+1) + ".txt"
        print(input_file_path)
        katakana_file_path = "./katakana/" + pref[pr] + "/talk" + "{:02}".format(i+1) + ".txt"
        print(katakana_file_path)
        extract_talk_and_write(input_file_path, katakana_file_path)
        print(pref[pr] + " " + "{:02}".format(i+1) + ": done")


山形 01: start
./input/山形/01Ⅰ山形01.txt
./katakana/山形/talk01.txt
###########################################################
山形 01: done
山形 02: start
./input/山形/01Ⅰ山形02.txt
./katakana/山形/talk02.txt
########################
山形 02: done
山形 03: start
./input/山形/01Ⅰ山形03.txt
./katakana/山形/talk03.txt
##################################################
山形 03: done
山形 04: start
./input/山形/01Ⅰ山形04.txt
./katakana/山形/talk04.txt
#########################
山形 04: done
山形 05: start
./input/山形/01Ⅰ山形05.txt
./katakana/山形/talk05.txt
##########################
山形 05: done
山形 06: start
./input/山形/01Ⅰ山形06.txt
./katakana/山形/talk06.txt
############################
山形 06: done
山形 07: start
./input/山形/01Ⅰ山形07.txt
./katakana/山形/talk07.txt
####################
山形 07: done
山形 08: start
./input/山形/01Ⅰ山形08.txt
./katakana/山形/talk08.txt
###################################
山形 08: done
山形 09: start
./input/山形/01Ⅰ山形09.txt
./katakana/山形/talk09.txt
##################
山形 09: done
山形 10: start
./input/山形/01Ⅰ山形10.txt
./katakana/山形

# pykakasi の導入

In [3]:
import pykakasi

kks = pykakasi.kakasi()

print(kks.convert("こんにちは、世界！"))

print(kks.convert("こんにちは、世界！")[0]["hepburn"])

words = kks.convert("アルキメデスの原理、とても面白いですね。カ゜、konnichiha, qaカ")

for word in words:
    print(word["hepburn"], end="")

[{'orig': 'こんにちは', 'hira': 'こんにちは', 'kana': 'コンニチハ', 'hepburn': 'konnichiha', 'kunrei': 'konnitiha', 'passport': 'konnichiha'}, {'orig': '、', 'hira': '、', 'kana': '、', 'hepburn': ',', 'kunrei': ',', 'passport': ','}, {'orig': '世界', 'hira': 'せかい', 'kana': 'セカイ', 'hepburn': 'sekai', 'kunrei': 'sekai', 'passport': 'sekai'}, {'orig': '！', 'hira': '！', 'kana': '！', 'hepburn': '!', 'kunrei': '!', 'passport': '!'}]
konnichiha
arukimedesunogenri,totemoomoshiroidesune.ka゜,konnichiha, qaka

In [4]:
# katakana フォルダ内のファイルを読み込んで、カタカナをローマ字に変換して roman フォルダに書き込む

def convert_handakuon(text):
    return text.replace("カ゜", "qa").replace("キ゜", "qi").replace("ク゜", "qu").replace("ケ゜", "qe").replace("コ゜", "qo").replace("テ゜", "de")

os.makedirs("./roman/", exist_ok=True)

for pr in range(number_of_pref):
    os.makedirs("./roman/" + pref[pr], exist_ok=True)
    if number_of_file[pr] == 0:
        continue
    for i in range(number_of_file[pr]):
        print(pref[pr] + " " + "{:02}".format(i+1) + ": start")
        katakana_file_path = "./katakana/" + pref[pr] + "/talk" + "{:02}".format(i+1) + ".txt"
        print(katakana_file_path)
        roman_file_path = "./roman/" + pref[pr] + "/roman" + "{:02}".format(i+1) + ".txt"
        print(roman_file_path)
        try:
            with open(katakana_file_path, "r", encoding="shift-JIS") as f:
                lines = f.readlines()
                for j in range(len(lines)):
                    lines[j] = convert_handakuon(lines[j])
        except Exception as e:
            print(f"Error reading {katakana_file_path}: {e}")
            continue

        try:
            with open(roman_file_path, "w", encoding="shift-JIS") as f:
                for line in lines:
                    roman = kks.convert(line)
                    for r in roman:
                        f.write(r['hepburn'])
                    f.write("\n")
        except Exception as e:
            print(f"Error reading {katakana_file_path} or writing {roman_file_path}: {e}")
            continue
        print(pref[pr] + " " + "{:02}".format(i+1) + ": done")

山形 01: start
./katakana/山形/talk01.txt
./roman/山形/roman01.txt
山形 01: done
山形 02: start
./katakana/山形/talk02.txt
./roman/山形/roman02.txt
山形 02: done
山形 03: start
./katakana/山形/talk03.txt
./roman/山形/roman03.txt
山形 03: done
山形 04: start
./katakana/山形/talk04.txt
./roman/山形/roman04.txt
山形 04: done
山形 05: start
./katakana/山形/talk05.txt
./roman/山形/roman05.txt
山形 05: done
山形 06: start
./katakana/山形/talk06.txt
./roman/山形/roman06.txt
山形 06: done
山形 07: start
./katakana/山形/talk07.txt
./roman/山形/roman07.txt
山形 07: done
山形 08: start
./katakana/山形/talk08.txt
./roman/山形/roman08.txt
山形 08: done
山形 09: start
./katakana/山形/talk09.txt
./roman/山形/roman09.txt
山形 09: done
山形 10: start
./katakana/山形/talk10.txt
./roman/山形/roman10.txt
山形 10: done
山形 11: start
./katakana/山形/talk11.txt
./roman/山形/roman11.txt
山形 11: done
山形 12: start
./katakana/山形/talk12.txt
./roman/山形/roman12.txt
山形 12: done
山形 13: start
./katakana/山形/talk13.txt
./roman/山形/roman13.txt
山形 13: done
山形 14: start
./katakana/山形/talk14.txt
./roman/山形/ro

In [5]:
# 大文字と小文字を区別せずにカウントするため、すべて小文字に変換する

# 各文字の出現回数をカウントして、出現回数の多い順に並べて出力する

# 各ディレクトリ内のファイルを読み込んで、ディレクトリ毎に文字の出現回数をカウントする
import collections

os.makedirs("./count/", exist_ok=True)

all_dict = {}

for pr in range(number_of_pref):
    if number_of_file[pr] == 0:
        continue
    count_file_path = "./count/" + pref[pr] + ".txt"

    dict = {}

    for i in range(number_of_file[pr]):
        print(pref[pr] + " " + "{:02}".format(i+1) + ": start")
        roman_file_path = "./roman/" + pref[pr] + "/roman" + "{:02}".format(i+1) + ".txt"
        print(roman_file_path)
        try:
            with open(roman_file_path, "r", encoding="shift-JIS") as f:
                lines = f.readlines()
        except Exception as e:
            print(f"Error reading {roman_file_path}: {e}")
            continue

        for j in range(len(lines)):
            lines[j] = lines[j].lower()
            # `'`, `.` は除外
            lines[j] = lines[j].replace("'", "").replace(".", "")
        
        count = collections.Counter()
        for line in lines:
            count.update(line)

        try:
            with open(count_file_path, "w", encoding="shift-JIS") as f:
                for c, n in count.most_common():
                    if c == "\n" or not c.isalpha():
                        continue
                    f.write(f"{c}: {n}\n")
                    dict[c] = dict.get(c, 0) + n
        except Exception as e:
            print(f"Error writing {count_file_path}: {e}")
            continue
        print(pref[pr] + " " + "{:02}".format(i+1) + ": done")

    for key, value in sorted(dict.items(), key=lambda x: -x[1]):
        print(f"{key}: {value}")
        all_dict[key] = all_dict.get(key, 0) + value

# all_dict を出現回数の多い順に並べて出力する

all_count_file_path = "./count/all.txt"

try:
    print("all: start")
    with open(all_count_file_path, "w", encoding="shift-JIS") as f:
        for c, n in sorted(all_dict.items(), key=lambda x: -x[1]):
            f.write(f"{c}: {n}\n")
            print(f"{c}: {n}")
    print("all: done")
except Exception as e:
    print(f"Error writing {all_count_file_path}: {e}")



山形 01: start
./roman/山形/roman01.txt
山形 01: done
山形 02: start
./roman/山形/roman02.txt
山形 02: done
山形 03: start
./roman/山形/roman03.txt
山形 03: done
山形 04: start
./roman/山形/roman04.txt
山形 04: done
山形 05: start
./roman/山形/roman05.txt
山形 05: done
山形 06: start
./roman/山形/roman06.txt
山形 06: done
山形 07: start
./roman/山形/roman07.txt
山形 07: done
山形 08: start
./roman/山形/roman08.txt
山形 08: done
山形 09: start
./roman/山形/roman09.txt
山形 09: done
山形 10: start
./roman/山形/roman10.txt
山形 10: done
山形 11: start
./roman/山形/roman11.txt
山形 11: done
山形 12: start
./roman/山形/roman12.txt
山形 12: done
山形 13: start
./roman/山形/roman13.txt
山形 13: done
山形 14: start
./roman/山形/roman14.txt
山形 14: done
山形 15: start
./roman/山形/roman15.txt
山形 15: done
山形 16: start
./roman/山形/roman16.txt
山形 16: done
a: 8962
n: 5737
e: 4739
o: 3888
d: 2797
u: 2391
h: 1842
r: 1741
i: 1671
t: 1635
s: 1512
k: 1472
g: 1320
m: 1131
y: 926
z: 640
b: 543
w: 341
c: 276
j: 190
p: 122
q: 114
f: 59
群馬 01: start
./roman/群馬/roman01.txt
群馬 01: done
群馬 02: sta

In [6]:
# 各都道府県において、各文字の含有率を計算する

rate_list_for_pref = []

for pr in range(number_of_pref):
    input_file_path = './count/' + pref[pr] + '.txt'
    rate_list = []
    try:
        with open(input_file_path, "r", encoding="shift-JIS") as f:
            lines = f.readlines()
    except Exception as e:
        print(f"Error reading {input_file_path}: {e}")
        continue

    total = 0
    for line in lines:
        if line == "\n":
            continue
        total += int(line.split(":")[1])

    for line in lines:
        if line == "\n":
            continue
        c, n = line.split(":")
        n = int(n)
        rate = n / total
        rate_list.append((c, rate))
    rate_list_for_pref.append(rate_list)


In [7]:
# 各都道府県の文字の含有率を読み込んで、グラフにプロットする

import matplotlib.pyplot as plt

os.makedirs("./rate/", exist_ok=True)

for pr in range(number_of_pref):
    rate_list = rate_list_for_pref[pr]
    if len(rate_list) == 0:
        continue
    print(pref[pr] + ": start")
    output_file_path = "./rate/" + pref[pr] + ".png"
    print(output_file_path)
    try:
        fig, ax = plt.subplots()
        ax.bar([r[0] for r in rate_list], [r[1] for r in rate_list])
        ax.set_xlabel("Character")
        ax.set_ylabel("Rate")
        ax.set_title(kks.convert(pref[pr])[0]["hepburn"])
        plt.savefig(output_file_path)
        plt.close()
    except Exception as e:
        print(f"Error writing {output_file_path}: {e}")
        continue
    print(pref[pr] + ": done")

# 母音と子音それぞれにおける含有率も計算する

vowels = "aeiou"
consonants = "bcdfghjklmnpqrstvwxyz"

vowel_rate_list_for_pref = []
consonant_rate_list_for_pref = []

for pr in range(number_of_pref):
    rate_list = rate_list_for_pref[pr]
    vowel_rate_list = []
    consonant_rate_list = []
    for c, rate in rate_list:
        if c in vowels:
            vowel_rate_list.append((c, rate))
        if c in consonants:
            consonant_rate_list.append((c, rate))
    vowel_rate_list_for_pref.append(vowel_rate_list)
    consonant_rate_list_for_pref.append(consonant_rate_list)

# 母音と子音の含有率を読み込んで、グラフにプロットする

os.makedirs("./vowel_rate/", exist_ok=True)
os.makedirs("./consonant_rate/", exist_ok=True)

for pr in range(number_of_pref):
    vowel_rate_list = vowel_rate_list_for_pref[pr]
    consonant_rate_list = consonant_rate_list_for_pref[pr]
    if len(vowel_rate_list) == 0 or len(consonant_rate_list) == 0:
        continue
    print(pref[pr] + ": start")
    output_file_path = "./vowel_rate/" + pref[pr] + ".png"
    print(output_file_path)
    try:
        fig, ax = plt.subplots()
        ax.bar([r[0] for r in vowel_rate_list], [r[1] for r in vowel_rate_list])
        ax.set_xlabel("Vowel")
        ax.set_ylabel("Rate")
        ax.set_title(kks.convert(pref[pr])[0]["hepburn"])
        plt.savefig(output_file_path)
        plt.close()
    except Exception as e:
        print(f"Error writing {output_file_path}: {e}")
        continue

    output_file_path = "./consonant_rate/" + pref[pr] + ".png"
    print(output_file_path)
    try:
        fig, ax = plt.subplots()
        ax.bar([r[0] for r in consonant_rate_list], [r[1] for r in consonant_rate_list])
        ax.set_xlabel("Consonant")
        ax.set_ylabel("Rate")
        ax.set_title(kks.convert(pref[pr])[0]["hepburn"])
        plt.savefig(output_file_path)
        plt.close()
    except Exception as e:
        print(f"Error writing {output_file_path}: {e}")
        continue
    print(pref[pr] + ": done")

山形: start
./rate/山形.png
山形: done
群馬: start
./rate/群馬.png
群馬: done
長野: start
./rate/長野.png
長野: done
奈良: start
./rate/奈良.png
奈良: done
高知: start
./rate/高知.png
高知: done
長崎: start
./rate/長崎.png
長崎: done
青森: start
./rate/青森.png
青森: done
新潟: start
./rate/新潟.png
新潟: done
愛知: start
./rate/愛知.png
愛知: done
福井: start
./rate/福井.png
福井: done
京都: start
./rate/京都.png
京都: done
島根: start
./rate/島根.png
島根: done
岩手: start
./rate/岩手.png
岩手: done
宮城: start
./rate/宮城.png
宮城: done
千葉: start
./rate/千葉.png
千葉: done
静岡: start
./rate/静岡.png
静岡: done
鳥取: start
./rate/鳥取.png
鳥取: done
愛媛: start
./rate/愛媛.png
愛媛: done
宮崎: start
./rate/宮崎.png
宮崎: done
山形: start
./vowel_rate/山形.png
./consonant_rate/山形.png
山形: done
群馬: start
./vowel_rate/群馬.png
./consonant_rate/群馬.png
群馬: done
長野: start
./vowel_rate/長野.png
./consonant_rate/長野.png
長野: done
奈良: start
./vowel_rate/奈良.png
./consonant_rate/奈良.png
奈良: done
高知: start
./vowel_rate/高知.png
./consonant_rate/高知.png
高知: done
長崎: start
./vowel_rate/長崎.png
./consonant_rate/長崎.png
長崎: 

In [8]:
# https://uub.jp/pdr/s/cap_4.html のデータを用いて、各都道府県の緯度経度と 各音素の含有率の相関を求める

lat_lon_for_pref = {
    "北海道": (43.06417, 141.34694),
    "青森": (40.82444, 140.74),
    "岩手": (39.70361, 141.1525),
    "宮城": (38.26889, 140.87194),
    "秋田": (39.71861, 140.1025),
    "山形": (38.24056, 140.36333),
    "福島": (37.75, 140.46778),
    "茨城": (36.34139, 140.44667),
    "栃木": (36.56583, 139.88361),
    "群馬": (36.39111, 139.06083),
    "埼玉": (35.85694, 139.64889),
    "千葉": (35.60472, 140.12333),
    "東京": (35.68944, 139.69167),
    "神奈川": (35.44778, 139.6425),
    "新潟": (37.90222, 139.02361),
    "富山": (36.69528, 137.21139),
    "石川": (36.59444, 136.62556),
    "福井": (36.06528, 136.22194),
    "山梨": (35.66389, 138.56833),
    "長野": (36.65139, 138.18111),
    "岐阜": (35.39111, 136.72222),
    "静岡": (34.97694, 138.38306),
    "愛知": (35.18028, 136.90667),
    "三重": (34.73028, 136.50861),
    "滋賀": (35.00444, 135.86833),
    "京都": (35.02139, 135.75556),
    "大阪": (34.68639, 135.52),
    "兵庫": (34.69139, 135.18306),
    "奈良": (34.68528, 135.83278),
    "和歌山": (34.22611, 135.1675),
    "鳥取": (35.50361, 134.23833),
    "島根": (35.47222, 133.05056),
    "岡山": (34.66167, 133.935),
    "広島": (34.39639, 132.45944),
    "山口": (34.18583, 131.47139),
    "徳島": (34.06583, 134.55944),
    "香川": (34.34028, 134.04333),
    "愛媛": (33.84167, 132.76611),
    "高知": (33.55972, 133.53111),
    "福岡": (33.60639, 130.41806),
    "佐賀": (33.24944, 130.29889),
    "長崎": (32.74472, 129.87361),
    "熊本": (32.78972, 130.74167),
    "大分": (33.23806, 131.6125),
    "宮崎": (31.91111, 131.42389),
    "鹿児島": (31.56028, 130.55806),
    "沖縄": (26.2125, 127.68111)
}

# 緯度と経度が変わることで 音素の含有率がどう変化するかを調べるため、緯度と経度の相関を求める

import numpy as np

vowels = "aoeiu"
consonants = "ntkshrmdygwbcjzqfp"

vowel_rate_list_for_pref = []
consonant_rate_list_for_pref = []

for pr in range(number_of_pref):
    rate_list = rate_list_for_pref[pr]
    vowel_rate_list = []
    consonant_rate_list = []
    for c, rate in rate_list:
        if c in vowels:
            vowel_rate_list.append((c, rate))
        if c in consonants:
            consonant_rate_list.append((c, rate))
    vowel_rate_list_for_pref.append(vowel_rate_list)
    consonant_rate_list_for_pref.append(consonant_rate_list)

lat_lon = []
vowel_rate = []
consonant_rate = []

for pr in range(number_of_pref):
    if len(vowel_rate_list_for_pref[pr]) == 0 or len(consonant_rate_list_for_pref[pr]) == 0:
        continue
    lat, lon = lat_lon_for_pref[pref[pr]]
    lat_lon.append((lat, lon))
    vowel_dict = {c: rate for c, rate in vowel_rate_list_for_pref[pr]}
    consonant_dict = {c: rate for c, rate in consonant_rate_list_for_pref[pr]}
    vowel_rate.append([vowel_dict.get(v, 0) for v in vowels])
    consonant_rate.append([consonant_dict.get(c, 0) for c in consonants])

lat_lon = np.array(lat_lon)
vowel_rate = np.array(vowel_rate)
consonant_rate = np.array(consonant_rate)

correlation_lat_vowel = np.corrcoef(lat_lon[:, 0], vowel_rate, rowvar=False)
correlation_lon_vowel = np.corrcoef(lat_lon[:, 1], vowel_rate, rowvar=False)
correlation_lat_consonant = np.corrcoef(lat_lon[:, 0], consonant_rate, rowvar=False)
correlation_lon_consonant = np.corrcoef(lat_lon[:, 1], consonant_rate, rowvar=False)

print(correlation_lat_vowel)
print(correlation_lon_vowel)
print(correlation_lat_consonant)
print(correlation_lon_consonant)

# 結果をグラフにプロットする

os.makedirs("./correlation/", exist_ok=True)

colors = plt.cm.tab20(range(len(vowels)))
fig, ax = plt.subplots(figsize=(10, 6))
for i in range(len(vowels)):
    ax.scatter(lat_lon[:, 0], vowel_rate[:, i], label=vowels[i],
               color=colors[i], alpha=0.8, s=50)
ax.set_xlabel("Latitude")
ax.set_ylabel("Rate")
ax.set_title("Vowel Rate")
ax.legend(loc='upper right', bbox_to_anchor=(1.1, 1.05), ncol=1)
plt.savefig("./correlation/vowel_rate_lat.png")
plt.close()

colors = plt.cm.tab20(range(len(vowels)))
fig, ax = plt.subplots(figsize=(10, 6))
for i in range(len(vowels)):
    ax.scatter(lat_lon[:, 1], vowel_rate[:, i], label=vowels[i],
               color=colors[i], alpha=0.8, s=50)
ax.set_xlabel("Longitude")
ax.set_ylabel("Rate")
ax.set_title("Vowel Rate")
ax.legend(loc='upper right', bbox_to_anchor=(1.1, 1.05), ncol=1)
plt.savefig("./correlation/vowel_rate_lon.png")
plt.close()

colors = plt.cm.tab20(range(len(consonants)))
fig, ax = plt.subplots(figsize=(11, 6))

for i in range(len(consonants)):
    ax.scatter(lat_lon[:, 0], consonant_rate[:, i], label=consonants[i],
               color=colors[i], alpha=0.8, s=50)
ax.set_xlabel("Latitude")
ax.set_ylabel("Rate")
ax.set_title("Consonant Rate")
ax.legend(loc='upper right', bbox_to_anchor=(1.1, 1.05), ncol=1)
plt.savefig("./correlation/consonant_rate_lat.png")
plt.close()

colors = plt.cm.tab20(range(len(consonants)))
fig, ax = plt.subplots(figsize=(11, 6))

for i in range(len(consonants)):
    ax.scatter(lat_lon[:, 1], consonant_rate[:, i], label=consonants[i],
               color=colors[i], alpha=0.8, s=50)
ax.set_xlabel("Longitude")
ax.set_ylabel("Rate")
ax.set_title("Consonant Rate")
ax.legend(loc='upper right', bbox_to_anchor=(1.1, 1.05), ncol=1)
plt.savefig("./correlation/consonant_rate_lon.png")
plt.close()

# 音素の含有率と緯度経度の相関係数を出力する

output_file_path = "./correlation/correlations.txt"

try:
    with open(output_file_path, "w", encoding="shift-JIS") as f:
        f.write("Vowel Rate\n")
        f.write("Latitude\n")
        for i in range(len(vowels)):
            f.write(f"{vowels[i]}: {correlation_lat_vowel[0, i+1]}\n")
        f.write("Longitude\n")
        for i in range(len(vowels)):
            f.write(f"{vowels[i]}: {correlation_lon_vowel[0, i+1]}\n")
        f.write("Consonant Rate\n")
        f.write("Latitude\n")
        for i in range(len(consonants)):
            f.write(f"{consonants[i]}: {correlation_lat_consonant[0, i+1]}\n")
        f.write("Longitude\n")
        for i in range(len(consonants)):
            f.write(f"{consonants[i]}: {correlation_lon_consonant[0, i+1]}\n")
except Exception as e:
    print(f"Error writing {output_file_path}: {e}")


[[ 1.          0.06585867 -0.22343995  0.76843732 -0.64888908  0.65473937]
 [ 0.06585867  1.         -0.58660199  0.18225    -0.49249375 -0.2398715 ]
 [-0.22343995 -0.58660199  1.         -0.26096959  0.33042669 -0.15965626]
 [ 0.76843732  0.18225    -0.26096959  1.         -0.70226628  0.41753205]
 [-0.64888908 -0.49249375  0.33042669 -0.70226628  1.         -0.52016384]
 [ 0.65473937 -0.2398715  -0.15965626  0.41753205 -0.52016384  1.        ]]
[[ 1.          0.19911114 -0.31215166  0.6684614  -0.55210233  0.38221633]
 [ 0.19911114  1.         -0.58660199  0.18225    -0.49249375 -0.2398715 ]
 [-0.31215166 -0.58660199  1.         -0.26096959  0.33042669 -0.15965626]
 [ 0.6684614   0.18225    -0.26096959  1.         -0.70226628  0.41753205]
 [-0.55210233 -0.49249375  0.33042669 -0.70226628  1.         -0.52016384]
 [ 0.38221633 -0.2398715  -0.15965626  0.41753205 -0.52016384  1.        ]]
[[ 1.          0.40900652 -0.5219678  -0.57877853 -0.00160759 -0.61463333
  -0.12212462 -0.3178921